name: Bug Report
description: Please do not use bug reports for if you have questions or need support.
labels: ['type:bug']
body:
  - type: markdown
    attributes:
      value: |
        Please use [Discord](https://discord.gg/voron) if you have questions or need support.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: model
    validations:
      required: true
    attributes:
      label: STL/Model file or files affected
      description: List each STL/Model that is affected
      placeholder: |
        [a]_latch-beta0.stl
        [a]_stealthburner_main_body_beta1.stl
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots to help explain your problem.
  - type: input
    id: slicer
    attributes:
      label: Slicer
      description: Please provide the slicer and version used
      placeholder: eg. SuperSlicer 2.3.57.8
    validations:
      required: true 
